name: "Todo Workflow"
 
on:
  push:
    branches: develop

  issues:
    name: Create Issues from Todos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: TODO to Issue
        id: todo
        uses: alstr/todo-to-issue-action@v2.0
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "// TODO:"
          COMMENT_MARKER: "//"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
